# Generated by Django 5.2.4 on 2025-07-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Укажите название курса', max_length=150, verbose_name='Название курса')),
                ('course_description', models.TextField(help_text='Укажите описание курса', verbose_name='Описание курса')),
                ('course_preview', models.ImageField(blank=True, help_text='Загрузите превью', upload_to='course_previews/', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(help_text='Укажите название урока', max_length=150, verbose_name='Название урока')),
                ('lesson_description', models.TextField(help_text='Укажите описание урока', verbose_name='Описание урока')),
                ('lesson_preview', models.ImageField(blank=True, help_text='Загрузите превью', upload_to='lesson_previews/', verbose_name='Превью')),
                ('link_to_the_video', models.URLField(help_text='Укажите ссылку на видео', verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['lesson_name'],
            },
        ),
    ]
